**Important:** First run the mongo data transfer with command:
`script/dumping_database.sh` 
since selenium-scraper folder

In [1]:
import os
HOST_MONGO = os.environ["SOCIALMONGO"]
MONGO_DB = os.environ["SOCIALMONGODB"]
print("HOST MONGO: ",HOST_MONGO)
print("DATA BASE:",MONGO_DB)

HOST MONGO:  mongodb://mongo:27017
DATA BASE: contents


## Importing mongo Collection

In [2]:
from pymongo import MongoClient
client = MongoClient(HOST_MONGO)
db = client[MONGO_DB]
posts = db['labeled_posts']
dictionaries = db['thematic_dictionaries']
print('Number of posts',posts.count())
print('Number of categories',dictionaries.count())

Number of posts 32302
Number of categories 180


In [153]:
thematic_to_number

{'fashion': 0, 'fitness': 2, 'food': 4, 'futbol': 5, 'makeup': 1, 'music': 3}

## Creating a DataFrames

In [204]:
import pandas as pd
df_posts = pd.DataFrame(list(posts.find()))

In [205]:
import numpy as np
df_dictionary = pd.DataFrame(list(dictionaries.find()))
thematics = set(df_dictionary["thematic"])
thematic_to_number = dict(zip(thematics,range(len(thematics))))
#thematic_to_number
dict_words_to_numeric = dict(zip(df_dictionary["word"],df_dictionary["thematic"].map(lambda x: thematic_to_number[x])))
df_posts["thematic_id"] = df_posts["thematic"].map(lambda x: dict_words_to_numeric[x])
df_posts

_id  \
0      59dd2801c25d306e2e4b1ebc   
1      59dd2801c25d306e2e4b1ebf   
2      59dd2801c25d306e2e4b1ec2   
3      59dd2801c25d306e2e4b1ec4   
4      59dd2801c25d306e2e4b1ec6   
5      59dd2801c25d306e2e4b1ec9   
6      59dd2801c25d306e2e4b1ecb   
7      59dd2801c25d306e2e4b1ecd   
8      59dd2801c25d306e2e4b1ecf   
9      59dd2801c25d306e2e4b1ed1   
10     59dd2801c25d306e2e4b1ed3   
11     59dd2801c25d306e2e4b1ed5   
12     59dd2802c25d306e2e4b1ed7   
13     59dd2802c25d306e2e4b1ed9   
14     59dd2802c25d306e2e4b1edb   
15     59dd2802c25d306e2e4b1edd   
16     59dd2802c25d306e2e4b1edf   
17     59dd2802c25d306e2e4b1ee1   
18     59dd2802c25d306e2e4b1ee3   
19     59dd2802c25d306e2e4b1ee5   
20     59dd2802c25d306e2e4b1ee7   
21     59dd2802c25d306e2e4b1eea   
22     59dd2802c25d306e2e4b1eec   
23     59dd2802c25d306e2e4b1eee   
24     59dd2802c25d306e2e4b1ef0   
25     59dd2802c25d306e2e4b1ef2   
26     59dd2802c25d306e2e4b1ef4   
27     59dd2802c25d306e2e4b1ef6   
28     59dd2802c25d306e2e4b1ef8   
29     59dd2803c25d306e2e4b1efa   
...                         ...   
32272  59f15b479b255e5fb874da18   
32273  59f15b4b9b255e5fb874da1b   
32274  59f15b4b9b255e5fb874da1d   
32275  59f15b4b9b255e5fb874da1f   
32276  59f15b4b9b255e5fb874da21   
32277  59f15b4b9b255e5fb874da23   
32278  59f15b4b9b255e5fb874da25   
32279  59f15b4b9b255e5fb874da27   
32280  59f15b4b9b255e5fb874da29   
32281  59f15b4b9b255e5fb874da2b   
32282  59f15b4b9b255e5fb874da2d   
32283  59f15b4b9b255e5fb874da2f   
32284  59f15b4b9b255e5fb874da31   
32285  59f15b4b9b255e5fb874da33   
32286  59f15b4b9b255e5fb874da35   
32287  59f15b4b9b255e5fb874da37   
32288  59f15b4b9b255e5fb874da39   
32289  59f15b4b9b255e5fb874da3b   
32290  59f15b4b9b255e5fb874da3d   
32291  59f15b4b9b255e5fb874da3f   
32292  59f15b4b9b255e5fb874da41   
32293  59f15b4b9b255e5fb874da43   
32294  59f15b4b9b255e5fb874da45   
32295  59f15b4b9b255e5fb874da47   
32296  59f15b4b9b255e5fb874da49   
32297  59f15b4b9b255e5fb874da4c   
32298  59f15b4b9b255e5fb874da4e   
32299  59f15b4b9b255e5fb874da50   
32300  59f15b4b9b255e5fb874da52   
32301  59f15b4b9b255e5fb874da54   

                                                   image network_type  \
0                                                             Twitter   
1        https://pbs.twimg.com/media/DLy93UHWkAAbrMk.jpg      Twitter   
2                                                             Twitter   
3        https://pbs.twimg.com/media/DLzU7fGW0AAjjtw.jpg      Twitter   
4                                                             Twitter   
5        https://pbs.twimg.com/media/DLwCLAwUQAAC1rD.jpg      Twitter   
6      https://pbs.twimg.com/ext_tw_video_thumb/91767...      Twitter   
7                                                             Twitter   
8        https://pbs.twimg.com/media/DLzIKExWAAADDqq.jpg      Twitter   
9        https://pbs.twimg.com/media/DLzULdmV4AAdIqc.jpg      Twitter   
10       https://pbs.twimg.com/media/DLy-54iX0AAJhbS.jpg      Twitter   
11       https://pbs.twimg.com/media/DLzQOOtWkAECyyy.jpg      Twitter   
12                                                            Twitter   
13     https://pbs.twimg.com/ext_tw_video_thumb/91780...      Twitter   
14       https://pbs.twimg.com/media/DLyhp5UVoAABZX0.jpg      Twitter   
15       https://pbs.twimg.com/media/DLuR53eW4AAsGGY.jpg      Twitter   
16       https://pbs.twimg.com/media/DLzOzUxW0AAuGze.jpg      Twitter   
17       https://pbs.twimg.com/media/DLywL1LXkAAYxYs.jpg      Twitter   
18     https://pbs.twimg.com/amplify_video_thumb/9178...      Twitter   
19                                                            Twitter   
20       https://pbs.twimg.com/media/DLynJQhXcAAnVZ9.jpg      Twitter   
21                                                            Twitter   
22       https://pbs.twimg.com/media/DLton40UIAABEVv.jpg      Twitter   
23       https://pbs.twimg.com/media/DLzOJ6PUIAASIY7.jpg      Twitter   
24                              

In [206]:
from sklearn.model_selection import train_test_split

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(df_posts['text'], 
                                                    df_posts['thematic_id'], 
                                                    random_state=0)

In [207]:
X_train.head()

12199    Grays\n.\n.\n.\n.\n#makeup #maquillaje #lotd #...
16338    Just 👉CR7\n\n#cristiano #cristianoronaldo #pag...
14968    Catch @NakuulMehta & @SurbhiChandna live today...
21382    Casual all blue top and jeans look #fashionblo...
30691    Joey Bada$$ Just Met Kobe Bryant At A Soccer G...
Name: text, dtype: object

## CountVectorizer

In [208]:
from sklearn.feature_extraction.text import CountVectorizer

# Fit the CountVectorizer to the training data
vect = CountVectorizer().fit(X_train)

In [209]:
vect.get_feature_names()[::2000]

['00',
 '2yytomx',
 'absorbent',
 'amasse',
 'astley',
 'bareminerals',
 'bikestable',
 'bravo',
 'calisthenicbabe',
 'chickenbake',
 'concursospublicos',
 'cutcreasemakeup',
 'developing',
 'drogashopmaysa',
 'enroll',
 'fantasyart',
 'flannel',
 'funcional',
 'glowfestas',
 'haireducation',
 'holiday',
 'incik',
 'itsyuvan',
 'kalıcımakyajistanbul',
 'kungfufighting',
 'likesplease',
 'lütfen',
 'maschera',
 'millions',
 'musclemania',
 'nicemitts',
 'olshopindo',
 'partymusic',
 'plans',
 'proposal',
 'recfit',
 'romweshop',
 'sdh',
 'silmo',
 'specially',
 'sultanas',
 'teams',
 'tlqdrzdjsh',
 'tyf',
 'vestidodequince',
 'westbromwichalbion',
 'ymodels',
 'детской',
 'производитель',
 'الصداقة',
 'لحية',
 'やっと着れる',
 '香港']

In [210]:
len(vect.get_feature_names())

105280

In [211]:
# transform the documents in the training data to a document-term matrix
X_train_vectorized = vect.transform(X_train)

In [212]:
from sklearn.linear_model import LogisticRegression
# Train the model
model = LogisticRegression()
model.fit(X_train_vectorized, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [213]:
model.score(X_train_vectorized,y_train)

0.98340625773961854

In [214]:
X_test_vectorized = vect.transform(X_test)
y_test_est = model.predict(X_test_vectorized)
model.score(X_test_vectorized,y_test)

0.87196631996037643

In [215]:
y_test_est

array([3, 1, 1, ..., 3, 0, 5])

In [216]:
from sklearn.metrics import confusion_matrix
c = confusion_matrix(y_test, y_test_est)
cantidad = c.sum(axis=1)
diagonal = c.diagonal()
accuracy = diagonal/cantidad
accuracy

array([ 0.86427567,  0.84840655,  0.85559006,  0.87866667,  0.88989442,
        0.89050036])

In [245]:
tw="carne"

In [246]:
model.predict(vect.transform(pd.Series(tw)))

array([5])

# Tfidf

In [179]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Fit the TfidfVectorizer to the training data specifiying a minimum document frequency of 5
vect = TfidfVectorizer(min_df=5).fit(X_train)

In [180]:
vect.get_feature_names()[::2000]

['00', 'comingsoon', 'gf', 'mans', 'renk', 'vegasstrong']

In [181]:
len(vect.get_feature_names())

10942

In [182]:
# transform the documents in the training data to a document-term matrix
X_train_vectorized = vect.transform(X_train)

In [183]:
from sklearn.linear_model import LogisticRegression
# Train the model
model = LogisticRegression()
model.fit(X_train_vectorized, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [186]:
model.score(X_train_vectorized,y_train)

0.91967307851069102

In [187]:
X_test_vectorized = vect.transform(X_test)
y_test_est = model.predict(X_test_vectorized)
model.score(X_test_vectorized,y_test)

0.86750866765725609

In [188]:
y_test_est

array([3, 1, 1, ..., 3, 0, 5])

In [189]:
from sklearn.metrics import confusion_matrix
c = confusion_matrix(y_test, y_test_est)
cantidad = c.sum(axis=1)
diagonal = c.diagonal()
accuracy = diagonal/cantidad
accuracy

array([ 0.85654008,  0.83290267,  0.85869565,  0.88666667,  0.88461538,
        0.87889775])

In [190]:
tw="Vimos e entramos, pq em viagem não somos desses que fazem reservas em restaurantes chiques kkkk Como o próprio nome diz, a hamburgueria oferece os burgers smash, carne fresca prensada direto na chapa, sem estarem moldados naquele formatinho redondinho que estamos acostumados. Lá não se usa carne congelada nem misturas industrializadas. 🍔Nós optamos pelo tradicional, o Classic Smash, com adicional de bacon, que por sinal estava uma delicia, tinha gostinho de bacon artesanal, da roça, sabe?"

In [191]:
model.predict(vect.transform(pd.Series(tw)))

array([5])

# n-grams

In [193]:
# Fit the CountVectorizer to the training data specifiying a minimum 
# document frequency of 5 and extracting 1-grams and 2-grams
vect = CountVectorizer(min_df=5, ngram_range=(1,2)).fit(X_train)

X_train_vectorized = vect.transform(X_train)

len(vect.get_feature_names())

21096

In [194]:
len(vect.get_feature_names())

21096

In [195]:
# transform the documents in the training data to a document-term matrix
X_train_vectorized = vect.transform(X_train)

In [196]:
from sklearn.linear_model import LogisticRegression
# Train the model
model = LogisticRegression()
model.fit(X_train_vectorized, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [197]:
model.score(X_train_vectorized,y_train)

0.97865929167010646

In [198]:
X_test_vectorized = vect.transform(X_test)
y_test_est = model.predict(X_test_vectorized)
model.score(X_test_vectorized,y_test)

0.86973749380881626

In [199]:
y_test_est

array([3, 1, 1, ..., 3, 0, 5])

In [200]:
from sklearn.metrics import confusion_matrix
c = confusion_matrix(y_test, y_test_est)
cantidad = c.sum(axis=1)
diagonal = c.diagonal()
accuracy = diagonal/cantidad
accuracy

array([ 0.86427567,  0.84582257,  0.85481366,  0.872     ,  0.89215686,
        0.88542422])

In [201]:
tw="Vimos e entramos, pq em viagem não somos desses que fazem reservas em restaurantes chiques kkkk Como o próprio nome diz, a hamburgueria oferece os burgers smash, carne fresca prensada direto na chapa, sem estarem moldados naquele formatinho redondinho que estamos acostumados. Lá não se usa carne congelada nem misturas industrializadas. 🍔Nós optamos pelo tradicional, o Classic Smash, com adicional de bacon, que por sinal estava uma delicia, tinha gostinho de bacon artesanal, da roça, sabe?"

In [203]:
model.predict(vect.transform(pd.Series(tw)))

array([4])